backend:
  name: github
  repo: the-chancery/the-chancery
  open_authoring: true
publish_mode: editorial_workflow
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "projects"
    label: "Projects"	    label: "Projects"
    folder: "content/projects"	    folder: "content/projects"
    create: true	    create: true
    fields:	    fields:
      - { label: "Title", name: "title", widget: "string" }	      - { label: "Title", name: "title", widget: "string" }
      - { label: "tester", name: "tester", widget: "datetime" }	      - { label: "tester", name: "tester", widget: "datetime" }
      - { label: "Publish Date", name: "date", widget: "datetime" }	      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }	      - { label: "Body", name: "body", widget: "markdown" }