backend:
  name: github
  repo: stockade-dev/stockade
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "page"
    label: "Page"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
  - label: "Project"
    name: "project"
    folder: "content/projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string", required: False }
      - { label: "URL", name: "url", widget: "string" }
      - {
          label: "Election Cycle",
          name: "election-cycle",
          widget: "datetime",
          date_format: YYYY,
        }
      - {
          label: "Organization",
          name: "organization",
          widget: "relation",
          collection: organization,
          search_fields: ["name"],
          value_field: "name",
          display_fields: ["name"],
          required: False
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "relation",
          collection: tag,
          search_fields: ["name"],
          value_field: "name",
          display_fields: ["name"],
          multiple: True,
          required: False
        }
  - label: "Organization"
    name: "organization"
    folder: "content/organizations"
    create: true
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Organization Type"
        name: "type"
        widget: "select"
        options:
          - { label: "Non-Profit", value: "nonprofit" }
          - { label: "Campaign", value: "campaign" }
          - { label: "Company", value: "company" }
          - { label: "Collective", value: "collective" }
      - label: "Funding"
        name: "funding"
        widget: "select"
        options:
          - { label: "Donations", value: "donations" }
          - { label: "Venture Capital", value: "vc" }
          - { label: "Bootstrapped", value: "bootstrapped" }
  - label: "Tag"
    name: "tag"
    folder: "content/tags"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
